* Gegenstaende
** Krakenauge
   :PROPERTIES:
   :CUSTOM_ID: KA1
   :TYP: Artefakt daemonisch
   :SRC: SH 91 SH 92
   :END:
   - Beschreibung :: eine unregelmäßig geformte, düster funkelnde, hühnereigroße Kugel,
     in der sich blaue, grüne und rote Schlieren bewegen
   - Wirkung :: *Charyptoroth Talisman*, der *Macht über Wesen aus der Tiefsee* verleiht.
     - erleichtert Beschwörungen von Dämonen aus Charyptoroths Gefolge um 3.
     - dauerhaft wirkenden Artefakt mit einem *HERR ÜBER DAS TIERREICH (20 FP)*,
       beschränkt auf Meereslebewesen aller Größenkategorien innerhalb von 16 Schritt Reichweite.
   - Kosten :: unbekannt
   - Preis :: unbezahlbar
   
   Die Wenigen, die seiner ansichtig wurden, berichten davon, dass das Auge
   ungeahnte Beeinflussung bei jenen ausübt, die in seine Schlieren schauen oder
   seinem *leisen Zischeln* lauschen.
   *Versprechungen von der Macht über das Meer* und über das eigene Schicksal
   scheinen dabei eine Schlüsselrolle zu spielen.

   *Letzte Sichtung* im Jahr 1035 BF bei der Brautschau des jungen Prinzen
   Finnian ui Bennain. Aber selbst unter Einsatz all ihrer Kräfte konnten die
   finsteren Kultisten nicht verhindern, dass das Krakenauge in den Fluten vor
   Havena versank, ohne sein böses Werk zu vollbringen.
   Bis heute *suchen* sowohl Abgesandte des Fürsten, die Hexen der Thorwaler,
   *Geweihte des Efferd* als auch die sich neu formierenden Anhänger der
   Charyb’Yzz nach diesem Kleinod, das ungeahnte Macht über die Bestien der
   Tiefsee und der Unterstadt verleihen soll

   Finsteren Gegenpart der Efferdperle. Viele, die des Auges ansichtig wurden,
   scheinen für den rechten Glauben verloren und folgen nun sinisteren Plänen.
   Es heißt ferner, dass die weise *Matriarchin Larona Seeträumerin* durch das
   Wirken des Krakenauges einen viel *zu frühen Tod* fand.

   Das Artefakt befindet sich inzwischen im Besitz von *Yonahoh* befindet.
   Offenbar hat sich der neue Anführer des Kultes noch nicht als würdig
   erwiesen, das Krakenauge zurückzuerhalten. Yonahoh beten sie als Sohn der
   Allesverschlingenden an, der dereinst Havena zerstören wird. Sobald sie von
   der Pforte des Grauens und der *Sternenmuschel* erfahren, werden sie
   versuchen, das Siegel zu stören.
** Efferdperle
   :PROPERTIES:
   :CUSTOM_ID: EP1
   :TYP: Artefakt goettlich
   :SRC: SH 93 
   :END:
   - Beschreibung :: eine wunderschöne, etwa hühnereigroße Perle von makelloser Reinheit
   - Wirkung ::
     - Erleichtert Zeremonien der Efferdkirche
     - Schutzkreis gegen Daemonen (u.A.), 6 Schritt
   - Kosten :: unbekannt
   - Preis :: unbezahlbar
** Tiefendorn
   :PROPERTIES:
   :CUSTOM_ID: item-tiefendorn
   :END:
   http://www.ulisses-gamereference.com/index.php/Tiefendorn.html

   - Der Dreizack des Alten Efferdtempels dient als Ritualobjekt bei Zeremonien der Geweihten
   - Er ist aus einem unbekannten, marinblau schimmernden Metall geschmiedet und mit
     Lapislazuli und Gwen Petryl geschmückt. Gravuren von Rochen und Quallen
     zieren Griff und Schaft.
   - Der Dreizack gehört seit uralten Zeiten dem Tempel, und manche glauben, er
     sei so alt wie das Gotteshaus selbst. Er soll zur Ermutigung und zum Kampf
     gegen Feinde des Glaubens dienen und letzteren atemlose Demut vor dem Gott
     des Meeres bescheren.
   
   Kamptechnick: Stangenwaffen
   - ﻿Waffe :: ﻿Tiefendorn (2H)
   - TP :: 1W6+5
   - L+S :: GE/KK 15
   - AT/PA-Mod :: 0/+1
   - RW :: lang
   - Gewicht :: 2 Stn
   - Länge :: 200 HF
   - Komplexität :: einf

   - geweiht (Numinoru)
   - unter Wasser gilt ein AT/PA-Mod von +2/+1
   - solange der Träger die Waffe in den Händen hält, kann er unter Wasser atmen
   - unter Wasser GS+2

   
