#+STARTUP: content
* NPCs 
  :PROPERTIES:
  :COLUMNS:  %28ITEM %3CUSTOM_ID(ID) %14OCCUPATION(BERUF) %7LOCATION(LOC) %3ORGANIZATION(ORG) %1SEX(GES) %12SRC
  :END: 
** Niamh Schlappmaul
   :PROPERTIES:
   :CUSTOM_ID: NS1
   :SEX:      w
   :OCCUPATION: Schreiberin
   :ORGANIZATION: Fanfare
   :LOCATION: UF11
   :SRC:      GN 14 SH 26
   :ORGANIZATION:
   :END:
   - Aussehen :: 40 Jahre, Rehaugen, breites Lächeln
   - Zitate ::
     - Habt ihr Informationen zu den Angriffen? Arbeitet ihr fuer die Efferdkirche?
     - In dramatischen Worten: Wie verlief die letzte Nacht?
     - Habt ihr schon mal jemanden getoetet? Wie fuehlte sich das an?
   - Rollenspiel ::
     - hektische Sprache & Bewegungen
     - zwanghaftes Blinzeln  
   - Hintergrund ::
     - Schreiberin der Fanfare
     - Schamlose Schnuefflerin
     - Versucht durch reisserische Bereichterstattung Auflage und Umsatz zu steigern
   - Ziele ::
     - Stoff fuer eine gute Story bekommen
     - Befragt die Helden (ggf. nach Patroullie)
       Je nach Umgang wird der spaetere Artikel die Helden abwerten oder idealisieren
   - Werte :: Willenskraft 12 (14/13/15)
   - Orte :: [[file:locations.org::#UF11][Redaktionshaus]]
*** Info [0/4]
    - [ ] [[file:locations.org::#T02][Efferdkirche]] sucht Recken zum Schutz der Buerger
    - [ ] Der H'Ranga Kult der Allesverschlingenden war in der Vergangenheit aktiv in Havena
          evtl. erstarkt der wieder
    - [ ] Konkurrierende Schmuggler die sich gegenseitig an die Kehle gehen
    - [ ] Die [[file:organizations.org::#SG1][Stadtgarde]] ist inkompetent und abergläubisch; im Gegensatz zu der [[file:organizations.org::#VG1][Vogtgarde]]
** Rohnwin ui Kerkill
   :PROPERTIES:
   :CUSTOM_ID: RK1
   :SEX:      m
   :OCCUPATION: Schreiber
   :ORGANIZATION: Fanfare
   :LOCATION: UF11
   :SRC:      GN 14 SH 26
   :ORGANIZATION:
   :END:
   - Aussehen :: 53 Jahre, tintenbefleckte Finger
   - Hintergrund ::
     - Schreiber der Fanfare
     - Verschwoerungstheoretiker
   - Ziele :: Auflage machen
   - Ort :: [[file:locations.org::#UF11][Redaktionshaus]]
** Gilia Delvenstein
   :PROPERTIES:
   :CUSTOM_ID: GD1
   :SEX:      w
   :OCCUPATION: Hauptfrau Garde
   :ORGANIZATION: SG1
   :LOCATION: OF11
   :SRC:      SH 108
   :END:
   - Aussehen :: 49 Jahre, korpulent, schlaff
   - Zitate :: "Habt ihr schon eine Kostuemidee fuer den Vollmondball auf der Rethis?"
   - Rollenspiel :: goennerhaft
   - Hintergrund ::
     - Kam durch gute Verbindungen an den Posten und füllt ihn nur so weit wie nötig aus
     - verbringt lieber Zeit im Badehaus, beim Ausritt oder im Immanstadion
   - Ziele ::
   - Orte :: [[file:locations.org::#OF11][Garnison]]
** Fackelbart
   :PROPERTIES:
   :CUSTOM_ID: FB1
   :SEX:      m
   :OCCUPATION: Gardist
   :ORGANIZATION: SG1
   :LOCATION: OF11
   :SRC:      SH 108
   :END:
   - Aussehen :: Erzzwerge, 89 Jahre, Monokel, rote Zoepfe & Bart
   - Zitate ::
   - Rollenspiel ::
     - pingelig
     - rechthaberisch
   - Hintergrund ::
     Eigentlich Tharex Sohn des Ulrax, ist Weibel und dient der Garde seit fünfzig Jahren.
     Er gilt als unerbittlichster Verfolger magischer Verbrechen.
     Er stützt seine Untersuchungen von Magie auf penibles Bücherwissen.
     Damit konnte er schon zu Unrecht Beschuldigte entlasten,
     hat aber auch Zauberwirker hinter Gitter oder auf den Scheiterhaufen gebracht.
   - Ziele :: magische Umtrieben zu entlarven & unterbinden
   - Orte :: [[file:locations.org::#OF11][Garnison]]
** Trode Torfstecher
   :PROPERTIES:
   :CUSTOM_ID: TF1
   :SEX:      m
   :OCCUPATION: Gardist
   :ORGANIZATION: SG1
   :LOCATION: OF11
   :SRC:      SH 108
   :END:
   - Aussehen :: 57 Jahre, blond, Schnauzer, rotbackig
   - Zitate :: "Gehen ein Elf und ein Zwerg in den Wald"
   - Rollenspiel :: ist meist für ein Schwätzchen zu haben
   - Hintergrund ::
     - lässt sich leicht um den Finger wickeln – besonders mit ein paar Münzen. 
     - Der Korporal sammelt Witze und ist immer erfreut, einen neuen zu hören
   - Ziele ::
     - schnelle Dukate machen und gute Zeit in der Schänke haben
   - Orte :: [[file:locations.org::#OF11][Garnison]]
** Obair Duggan
   :PROPERTIES:
   :CUSTOM_ID: OD1
   :SEX:      m
   :OCCUPATION: Hauptmann Seekrieger
   :ORGANIZATION: HS1
   :LOCATION: FI05
   :SRC:      SH 108
   :END:
   - Aussehen :: 58 Jahre, ergraut
   - Zitate ::
   - Rollenspiel ::
     - offen & freudlich
   - Hintergrund :: Hauptmann der Havener Seekrieger
   - Ziele ::
   - Orte :: [[file:locations.org::#FI05][Garnison der Seekrieger]]
** Ardach Herlogan
   :PROPERTIES:
   :CUSTOM_ID: AH1
   :SEX:      m
   :OCCUPATION: Stadtvogt
   :ORGANIZATION:
   :LOCATION: OF03
   :SRC:      SH 46 SH 70 SH131
   :END:
   - Aussehen :: 58 Jahre, klein gewachsen, braune Locken, buschiger Vollbart
   - Zitate ::
     Das *Problem des Schmuggels* ist nicht, dass zu wenige Gardisten hinschauen,
     sondern dass zu viele wegschauen.
     Die eine Hälfte hat schmuggelnde Freunde oder Verwandte, die andere Hälfte
     genießt feine Gewürze, Premer Feuer und Rauschkraut aus den Hehlerkellern.
     Und allen gemeinsam ist, dass sie schlottern und winseln, wenn sie nachts
     auf dem Bennain-Damm wachen oder mit Booten in die Unterstadt fahren sollen
   - Rollenspiel ::
     - charismatischer Menschenkenner
   - Hintergrund ::
     - Stadtvogt von Havena, Markvogt der Stadtmark Havena und *Edler von Glydwick*
     - Die Herlogans sind ein *uraltes Adelsgeschlecht* im Besitz von viel Land.
       Sie sind manchmal etwas melancholisch, behaupten, seit der Stadtgründung
       zu Havena zu gehören und von Feen abzustammen.
     - *Herrscht ueber Havena* als Stellvertreter des Fürsten.
     - Verwahrt die Stadtsymbole wie Schlüssel und Siegel und nimmt
       repräsentative Aufgaben für Havena wahr.
     - Er sorgt für den *Stadtfrieden* sowie die Sicherheit der Stadtmauern. die
       Vogtgarde untersteht seinem Befehl. Ardach Herlogan sitzt bei schweren
       Verbrechen selbst zu Gericht und fällt Urteile im Namen des Fürsten.
     - Aus dem politischen Alltag hält sich der Stadtvogt oft heraus, er hat
       aber gegenüber den Beschlüssen des Ältestenrats und des Rats der Kapitäne
       ein fürstliches Vetorecht.
     - Herlogan ist ein *Machtmensch ohne Skrupel*, der schon als junger Mann
       seine Eltern und seinen älteren Bruder bei einem „Unglück“ auf dem Großen
       Fluss beiseite schaffen ließ, um das Familienerbe anzutreten. Er predigt
       hohe Werte und *schimpft auf den Schmuggel*, mischt aber selbst über Dritte
       kräftig im *Schattenhandel* mit Rauschkraut und Luxuswaren bis hin zum
       Verschleppen von Neckern mit.
     - Zensiert jede Ausgabe der Fanfare.
   - Ziele ::
     - Macht wahren & ausbauen
     - Profit durch Schmuggel
     - Informationen sammeln: Was geht in Havena vor sich; wer sind die relevanten Akteure
   - Werte :: Willenskraft 15 (14/15/16)
   - Orte :: [[file:locations.org::#OF03][Haus des Stadtvogts]]
** Ranziger Toss
   :PROPERTIES:
   :CUSTOM_ID: RT1
   :SEX:      m
   :OCCUPATION: Imman Ausputzer
   :ORGANIZATION: NG1
   :LOCATION: G08 HA
   :SRC:      SH 69 SH 131
   :END:
   - Aussehen :: 29 Jahre, massig (riesenhaft), Kapitänshut
   - Zitate :: Mit dir wisch' ich den Boden auf
   - Volkes Stimme ::
     Bullen vor! Bullen vor!
     Wer ist im Stall das beste Ross? Der Ranzige Toss!
     Freudig der Stürmer nach vorne schoss. Doch er prallte dort nur auf den Toss!
   - Rollenspiel ::
     - grimmig, lächelt nicht
     - laut, brüllt Kommandos, schmettert Lieder
   - Hintergrund ::
     - Toss stammt aus den Gassen des *Orkendorfs* und pflegt zuhause seine kranke Mutter.
     - Arbeitet als *Ewerführer* im Hafen (steuert flache Lastkähne im Hafen)
     - Blocker bei den Havena Bullen
     - Anführer der Nebelgeister (*Graf der Unterstadt*).
     - Als Schmuggler ist er erstaunlich geschickt, kann gut schleichen und weiß
       die Bandenmitglieder auf sich einzuschwören.
       Er ist ein kräftiger Kämpfer mit Hiebwaffen und Wurfaxt.
     - Wenn er gefasst wird, hofft er darauf, von einem Bullen Fan laufen gelassen zu werden.
   - Ziele ::
     - Geld beiseite schaffe und als Schmuggler unentdeckt bleiben
     - Kariere bei den Havena Bullen so lange wie moeglich, als Deckmantel
     - Beziehungen ausbauen
   - Werte :: Willenskraft (15/13/12)
   - Orte ::
     - [[file:locations.org::#HA][Hafen]]
     - [[file:locations.org::#G08][Esche und Kork]]
   - Organisationen ::
     - [[file:organizations.org::#NG1][Nebelgeister (Verwegene Schmuggler)]]
     - Havena Bullen (Imman Manschaft)
   - Anekdote :: Als eine Hafenarbeiterin ausrutschte und zwischen Hafenkai und
     die Bordwand einer 20 Schritt langen Kogge fiel, reagierte er sofort: Toss
     drückte das Schiff mit aller Kraft fort, bis selbst die Anlegeleine riss,
     und rettete so die Frau davor, zerquetscht zu werden.
** Lyn Barc, der Aal
   :PROPERTIES:
   :CUSTOM_ID: LB1
   :SEX:      w
   :OCCUPATION: Schmugglerin
   :ORGANIZATION: NG1
   :LOCATION: G08 HA
   :SRC:      SH 105
   :END:
   Schmugglerin
   - Aussehen :: 45 Jahre, klein und drahtig, graues Strubbelhaar
   - Rollenspiel ::
     - trockener Humor
   - Hintergrund ::
     - Streunerin
     - rechte Hand von [[#RT1][Ranziger Toss]]
     - Liebhaberin von Wein, Tabak und Rauschkraut
     - als Verbündete treu, als Gegnerin aber mit allen Wassern gewaschen, und
       sie schneidet auch Kehlen durch, wenn es sein muss
   - Ziele ::
     - guter Rausch & Profit
   - Werte :: Willenskraft 9 (14/13/12)
   - Orte ::
     - [[file:locations.org::*Hafen (HA)][Hafen]]
     - [[file:locations.org::#G08][Esche und Kork]]
** Thalionmel Agilfied, Thal das Blümchen
   :PROPERTIES:
   :CUSTOM_ID: TA1
   :SEX:      w
   :OCCUPATION: Wirtin
   :ORGANIZATION: NG1
   :LOCATION: G08
   :SRC:      SH 71 SH 105 SH 132 SK 21
   :END:
   Wirtin der Esche & Kork
   - Aussehen :: Auelfe, 58 Jahre, schwarzhaarig, schwarze Augen mit Blauschimmer, feine Züge
   - Zitate :: "Setzt euch! Ich bring euch erstmal eine Runde Premer Feuer!"
   - Rollenspiel ::
     - bezaubernd, abenteuerlustig
   - Hintergrund ::
     - Wirtin [[file:locations.org::#G08][Esche und Kork]]
     - von allen geschätzte Erscheinung, die zu Havena gehört wie der Hafen
     - Thalionmel hofft immer auf Nachricht von ihrer Zwillingsschwester Aldare,
       die das Fernweh in die weite Welt getrieben hat
     - Sie hat eine *Schwäche für abenteuerlustige Männer*
   - Ziele ::
     - die Taverne fuehren (unaufaellig, um als Treffpunkt der Nebelgeist nicht aufzufallen)
     - ihre Schwester Aldare finden
   - Werte :: intuitive Zauberin
     - SK 3
     - Handel 12 (13/14/15)
     - Menschenkenntnis 12 (13/14/15)
     - Willenskraft 10 (13/14/15)
     - Bannbaladin 7 (14/14/15)
     - Sensibar 6 (14/14/15)
   - Orte :: [[file:locations.org::#G08][Esche und Kork]]

   - Ihr Ziehvater Sulpiz zog Thalionmel und ihre Schwester als Findelkinder gross.
     Nachdem er ihnen gestand, zog Aldare hinaus in die Welt um die verschollene Mutter zu finden.
** Seola, der Falke
   :PROPERTIES:
   :CUSTOM_ID: SF1
   :SEX:      w
   :OCCUPATION: Schmugglerin
   :ORGANIZATION: NG1
   :LOCATION: UF01
   :SRC:      SH 105
   :END:
   - Aussehen :: 45 Jahre, derb, abenteuerlustig
   - Rollenspiel ::
     - blind
   - Hintergrund ::
     - führt trotz ihrer Blindheit die Transporte dank ihres guten Gehörs und
       sechsten Sinns für Gefahr sicher durch die Unterstadt.
     - Tagsüber pflegt sie Kranke im [[file:locations.org::#UF01][Siechenhaus]].
** Mhoran Dhonn, der Zwirbel
   :PROPERTIES:
   :CUSTOM_ID: MD1
   :SEX:      m
   :OCCUPATION: Werftarbeiter
   :ORGANIZATION: NG1
   :LOCATION: S01
   :SRC:      SH 105
   :END:
   - Aussehen :: 37 Jahre, knollennasig, langer und gepflegter Bart, Holzbein (mit Geheimfach)
   - Rollenspiel ::
     - zwirbelt seinen Bart
   - Hintergrund ::
     - hält Werkzeuge und die Boote der Bande in Schuss, die bei seinem Haus in Südhafen lagern
   - Orte :: Werft im Suedhafen
** Dunvall und Cynvall
   :PROPERTIES:
   :CUSTOM_ID: DC1
   :SEX:      m
   :OCCUPATION: Hafenarbeiter
   :ORGANIZATION: NG1
   :LOCATION: HA
   :SRC:      SH 105
   :END:
   - Aussehen :: Zwillinge 22 Jahre, schwarze Schnauzer, hünenhaft
   - Hintergrund ::
     - Ruderer und Lastenschlepper.
     - Am Tag arbeiten die Zwillinge als Schauermänner am Hafen
   - Orte :: [[file:locations.org::#HA][Hafen]]
** Leohain Stoertenbecher
   :PROPERTIES:
   :CUSTOM_ID: GC1
   :SEX:      m
   :OCCUPATION: Schmuggler
   :ORGANIZATION: NG1
   :LOCATION: Moorburg
   :SRC:      SH 43 SH 106
   :END:
   - Aussehen :: 26 Jahre braunhaarig, Galgenhumor (Knöcherner)
   - Hintergrund ::
     - Bruder von *Leowald*
     - Hat für die Bande den Kopf hingehalten und sitzt in der Moorburg. Die
       anderen versprachen, für ihn zu sorgen und ihn rauszuholen. Doch seit
       einiger Zeit kommt das Geld für Galwins gute Haftbedingungen nicht mehr
       an, sodass er im Knochenturm leidet. Galwin verliert langsam das
       Vertrauen in seine Kumpane und steht kurz davor, die Nebelgeister zu
       verraten.
   - Ziele ::
     - rauskommen 
     - dichthalten
   - Orte :: Moorburg
** Wilanna, die Moevenfrau
   :PROPERTIES:
   :CUSTOM_ID: WM1
   :SEX:      w
   :OCCUPATION: Bettlerin
   :ORGANIZATION: NG1
   :LOCATION: HA
   :SRC:      SH 71 SH 106
   :END:
   - Aussehen :: 28 Jahre, Glubschaugen, verfilztes Haar, bedeckt mit Möwenkot,
     zerschlissene Admiralsuniform der Westflotte
   - Zitate :: "KNA, KNA, KNA, KAN!" Moevengeschrei nachahmend
   - Rollenspiel ::
     - wirr fuchtelnd & krakeelend
   - Hintergrund ::
     - wird dort zu Hilfe gerufen, wo die Seevoegel es zu penetrant treiben
     - *krakeelt* minutenlang mit den Möwen, führt einen *wirren Tanz* auf und balgt
       sich mit ihnen um Fischabfall. Dann fliegen sie weg.
     - hetzt Moeven auf unliebsamme Zeitgenossen
     - Nutzt ihre Tiere auch als *Boten*. Sie lässt sich mit einer Empfehlung
       von Vertrauten ([[*Lyn Barc, der Aal][Lyn Barc]], Imo Wolter) für einige Silbertaler dafür
       anwerben, kleine Dinge (bis 3 Unzen Gewicht) an Vogelbeinen bis zu zehn
       Meilen weit fliegen zu lassen, etwa zu einem Schiff an der Küste.
   - Ziele ::
     - den perfekten Einklang mit den Moeven zu finden
     - ist auf der Suche nach dem Tierkoenig der Seevoegel
   - Werte :: Magiedilettantin (Einfluss)
   - Orte ::
     - Nachmittags [[file:locations.org::#FI06][Fischmarkt]]
     - schlaeft nachts am [[file:locations.org::*Hafen (HA)][Hafen]]kai, bedeckt von Moevenleibern
** Idra Kerkil
   :PROPERTIES:
   :CUSTOM_ID: IK1
   :SEX:      w
   :OCCUPATION: Zoellnerin
   :ORGANIZATION: SH1
   :LOCATION: HA
   :SRC:      SH 71 SH 106
   :END:      
   - Aussehen :: 39 Jahre, korpulent
   - Zitate :: "Hamm se was zu verzollen die Herrschaften?"
   - Rollenspiel :: schwatzhaft
   - Hintergrund ::
     - wickelt die wichtigsten Warendurchgänge ab,
     - hat zur Absicherung etliche Transaktionen in einem versteckten Buch niedergelegt
   - Ziele ::
     - Reich werden & Einfluss gewinnen
   - Orte :: [[file:locations.org::#SÜ10][Zollbrücke]]

   Zentrale Person auf dem Silberpfad. Organisiert eingeweihte Zöllner.
** Meriwen Bleichbruck
   stellvertretende Kontorleiterin
   :PROPERTIES:
   :CUSTOM_ID: MB1
   :SEX:      w
   :OCCUPATION: Kontorleiterin
   :ORGANIZATION: SH1
   :LOCATION: NA03
   :SRC:      SH 70 SH 106
   :END:
   - Aussehen :: 43 Jahre, 1,65 Schritt, schwarzer Pagenschnitt, stechende graue Augen,
     Goldohrring im linken Ohr
   - Zitat :: "Was darf ich euch besorgen?"
   - Rollenspiel ::
     - kuehl und *berrechnend*, gerissen & vorsichtig
     - zupft am Ohring
   - Hintergrund ::
     - *stellvertretende Kontorleiterin* des Handelshauses *Engstrand*
     - zuverlässigste Ansprechpartnerin, um Handelswaren aller Art zum gewünschten Termin zu erhalten
     - erfahrene Kauffrau und Kapitänin verhandelt hart mit Kunden, Verkäufern oder Dieben und Piraten
     - Kontrolliert den Schmuggel der [[file:organizations.org::#SH1][Silbernen Hand]] auf dem Silberpfad
       - Sie kann so gut wie alles besorgen wenn der Preis stimmt.
       - Sie kann zahllose Hebel in Havena in Bewegung setzen und
         hat darüber hinaus Verbindungen von Grangor bis Thorwal.
       - Ihre Unternehmungen plant sie sorgfältig, um die Risiken zu minimieren.
   - Ziele ::
     - stetig Reichtum mehren um in den Stadtadel aufzusteigen
     - die Nebelgeister schwaechen, da sie den Profit der Silbernen Hand schmälern
   - Werte :: Willenskraft 13 (14,15,13)
   - Orte ::
     - [[file:locations.org::#NA03][Kontor Engstrand]]
*** Info [0/5]
    - [ ] Verbindung zu Axel ueber Handel mit Familie von Aue
    - [ ] zu den *Angriffen*
      - Eindringling von den Wachleuten & Hunden vertrieben; entkommen in Kanal:
        - Wiederlich nach Fisch stinkend
        - mit Muscheln & Tang bewachsen?
        - leutend gruene Augen 
      - "Wuerde mich nicht wundern, wenn die Nebelgeister hinter den Angriffen stecken;
         die Angst nuetzt hinen!"
    - [ ] Schmuggel der [[file:organizations.org::#NG1][Nebelgeister]] ist ein grosses Problem fuer den Handen & Sicherheit von Havena
          auch der Stadtvogt [[#AH1][Ardach Herlogan]] sieht den Schmuggel als grosses Problem
    - [ ] *Auftrag*: Das Geflecht aus Schmugglern, Hehlern & Nutznießern zerschlagen
          zahlt fuer Informationen und Kopfpraemien fuer gefangene Schmuggler;
          kein unmittelbares Interesse an Hehlern (das sie ja auch die Ware der Silbernen Hand absetzen)
    - [ ] [[file:plot.org::#5][Vollmondball auf der Rethis]]
** Simiadane Spectalli, Mechanica
   :PROPERTIES:
   :CUSTOM_ID: SM1
   :SEX:      w
   :OCCUPATION: Erfinderin
   :ORGANIZATION: 
   :LOCATION: UF10
   :SRC:      SH 66 SH 129
   :END:
   - Aussehen :: 55 (36) Jahre, blondes wirres Haar, Furunkel auf der Strin, Arbeitsschürze
   - Zitate :: Vertüftelt noch eins! Was sagt Ihr Cavalliere Cranium?
     Meine Sprungfederfüße für pedestrische Beschleunigung ziehen nach links?
     Unmöglich, meine Berechnungen stimmen immer! Na schön.
     Ich schau sie mir noch mal an. Dieses Mal werden sie per-fekt!«
   - Rollenspiel ::
     - nervös, wunderlich
     - führt Selbstgespräche mit dem Furunkel auf ihrer Stirn , das sie *Cavalliere Cranium* nennt 
   - Hintergrund ::
     - begeisterte Mechanica, hoch konzentriert auf ihre Arbeit
     - letzte *Lehrling des legendären Leonardo*, ehe dieser 1020 BF entführt wurde
     - Verliess mit 16 Havena und kehrte nach Wanderjahren im Sueden mit
       *Leonardos Testament* zurueck und beanspruchte Werkstatt und Patente des Meisters
     - fortschrittsfeindlicher Bürger zweifeln die Echtheit des Testaments an
     - Fürst *Finnian bestätigte Simiadanes Anspruch* auf das Erbe unter zwei Bedingungen:
       - Neue Erfindungen muss sie zuerst dem Fürstenhof zum Kauf anbieten.
       - Alle zwei Wochen muss sie zur Überprüfung ihres Seelenheils einen Praiosgeweihten aufsuchen.
   - Ziele ::
     - Will ihre Erfindungen testen lassen (Verbesserung)
     - Will ihr Geheimnis bewahren 
   - Werte :: Willenskraft
   - Orte :: [[file:locations.org::#UF10][Simiadanes Werkstatt]]

   Hinter Simiadane verbirgt sich die Mechanika *Heliantha Ugolinez* aus Alanfa.
   - sie ist keine Schülerin Leonardos, sondern studierte an der Universität
     Al’Anfa beim Mechanikus Protasius Aurelius, einem langjährigen Konkurrenten Leonardos
   - Heliantha lernet Simiadane im Horasreich kennen und nahm ihre Rolle ein als
     sie von ihrem Verschwinden erfuhr
   - der Praiosgeweihten Ulodan kennt ihre Luege, verraet sie aber nicht, da er in sie verliebt ist
*** Info [0/2]
    - [ ] Auftrag: Alte mechanische Geraete aus dem [[file:locations.org::#MA01][Theater an der Gauklergasse]] besorgen
          die Aschimeter dort einst zusammenbaute
    - [ ] Befreundet mit [[#BH1][Branwen]]; diese ist mit [[*Ybalio][Ybalio]] dem Necker liiert
** Branwen, die Hexe
   :PROPERTIES:
   :CUSTOM_ID: BH1
   :SEX:      w
   :OCCUPATION: Schatzsucherin
   :ORGANIZATION: 
   :LOCATION:
   :SRC:      SH 67 SH 130
   :END:
   - Aussehen :: 28 Jahre, gutaussehend, rotes Haar, grüne Augen
   - Zitate :: Da drüben! Da könnte ein Tauchgang lohnen.
     Ich spüre es, es kribbelt richtig auf meiner Haut. Wie? Magisch? Ich? Nein
   - Rollenspiel ::
     - faehrt mit der Hand durchs lange Haar
   - Hintergrund ::
     - Schatzsucherin in der Unterstadt
     - sucht in der Unterstadt nach ihrem verschollenen Vater
     - ist liiert den Necker *Ybalio*, der sie haeufig in die Unterstadt begleitet
   - Ziele ::
     - ihren Vater *Taranion* finden (der lebt auf der Karavelle *Meerschaum*)
   - Orte :: [[file:locations.org::*Nalleshof (S07)][Nalleshof]]

   - Branwen besitzt ein Boot (6 Personen) im [[file:locations.org::#S01][Südhafen]].
   - In Fischerort begegnet der schönen Rothaarigen oft Missgunst.
     *Frauen hassen sie*, weil etliche Männer ihrem Liebreiz verfallen.
     In den Gassen flüstert man, *sie sei eine Hexe*, die mit unheiligen Mächten im Bunde sei.
   - Branwen ist *Magiedilettantin*
     - Bannbaladin
     - Horriphobus
     - Magisches Gespür für Schatzsuche in der Unterstadt (Begegnungen -1 SH 119, Schatz +3 SH 120)
** Cullain Nebelstecher
   :PROPERTIES:
   :CUSTOM_ID: CN1
   :SEX:      m
   :OCCUPATION: Seelotse
   :ORGANIZATION:
   :LOCATION: Hafen
   :SRC:      SH 66
   :END:
   - Aussehen :: 32 Jahre, braunes Haar, gutaussehend, verschmitzt
   - Zitate :: Jetzt sechs Strich steuerbord für 30 Schlag.
     Steuerbord habe ich gesagt, du Dösbroodel, nicht backbord!
     Oder willst du dich mit dem Kahn zu den Robben legen?
   - Rollenspiel ::
     - **Pfeife schmauchend*
   - Hintergrund ::
     - Cullain ist ein Havener Original. Der charmante Seelotse kennt jede
       Sandbank zwischen Hafen und Mündung und bringt Schiffe von der kleinen
       Kogge bis zur Viermastschivone selbst bei dichtem Nebel sicher durch die Fahrrinnen.
     - Er liebt Geschichten, erzählt gerne Seemannsgarn, trägt jedes Gerücht
       weiter und weiß, was in Havena vor sich geht.
       Wettrunden und Boltantischen kann er kaum widerstehen und setzt gerne auf eine gute Gelegenheit.
     - *Schürzenjäger*
   - Ziele ::
   - Orte :: [[file:locations.org::#HA][Hafen]], Lotseninsel

   Spiel- und Wettschulden bringen Cullain regelmäßig in Schwierigkeiten.
*** TODO Info [2/4]
    - [X] du haettest [[#RT1][Ranziger Toss]] bei Spiel gegen Bleichmuräne Unterstadt sehen sollen!
    - [X] [[file:plot.org::#3][Naechtliche Angriffe in Havena]], *Ysilt Bennoch* wurde in Krakendorf erstochen
    - [ ] vor einigen Jahren Umtriebe des Kultes der *Allesverschlingenden*
          wahnsinniger Thorwaler Kultist; seitdem verstaerkte Umtriebe
    - [ ] ist oft im [[file:locations.org::#G08][Esche und Kork]] und kann sich dort mit den Helden treffen
    - [ ] *Unterstadt*: vor 300 Jahren von der grossen Flut ueberschwemmt
      - überflutete Schwemmlandschaft voller sumpfiger Inselchen und schweigender Ruinen.
      - Ausdehnung von 1,5 auf 2 Meilen etwa doppelt so groß wie das heutige Havena
      - Schatzsucher, Verbrecher, Schmuggler und Kultisten treiben sich dort hermum
      - betreten ist Verboten (vom Fuerstenhaus)
      - [[#BH1][Branwen]] und [[#OF1][Ordhan Faic]] kennen sich dort gut aus, sie sind oft in der [[file:locations.org::*Schatzinsel][Schatzinsel]]
      
** Lata, Drachenschildkroete
   :PROPERTIES:
   :CUSTOM_ID: LA1
   :SEX:      w
   :OCCUPATION: Sendbotin Efferds
   :ORGANIZATION: EK1
   :LOCATION: LK
   :SRC:      SH 110
   :END:
   - Aussehen :: 12 Schritt lang, 4 Schritt hoch
     - der *uralte Schildkroetenpanzer* trägt Muscheln, Seepocken zahllosen Narben erbitterter Kämpfe
     - Der Kopf ist von einem *Hornkamm* geschmückt
     - Ihre gütigen, gelben Augen sind tellergroß und blinzeln selten
   - Zitate ::
     - Heilige Lata! (Ausruf des Erstaunens)
   - Rollenspiel ::
     - uralt, weise & langmuetig
     - freundlich & vertrauensselig gegenueber Sterblichen
   - Hintergrund ::
     - kam kurz nach der grossen Flut nach Havena
   - Kommunikation :: per *Gedankensprache*.
     - wählt als Gegenüber einen intuitiven Magiebegabten (Hexe, Elf)
     - Die Worte, Eindrücke und Bilder steigen wie eine Springflut im verbundenen Geist an.
       Lata *beginnt meist mit einfachen Botschaften*, die immer komplexer werden.
       Oft werden ihre Gedanken so stark und intensiv, dass ein Mensch sie kaum noch erfassen kann,
       im Bildersturm ertrinkt und noch Stunden oder Tage später in der Erinnerung neue Details findet.
       Empfänger erwachen oft nach dem „Gespräch“ keuchend und mit blutender Nase im Sand der Kaverne.
   - Ziele ::
     - Die *Pforte des Grauens bewachen* und dafuer sorgen, dass sie geschlossen bleibt
     - gegen charyptiden Wesen kaempfen und sie vernichten
   - Fähigkeiten :: fremdartige, animalische Magie 
     - magische Wellen der Zerstörung gegen Feinde zu senden
     - in die Vergangenheit zu blicken
     - Tore in nahe Feenwelten zu öffnen.
     - Sie kann Landlebewesen die Fähigkeit zur Wasseratmung geben
     - den Eingang zu ihrer Kaverne verhehlen
   - Orte :: [[file:locations.org::#LK][Latas Kaverne]]

   Die mächtige Drachenschildkröte gilt den Havenern als heiliges Wesen und das
   Zeichen, dass Efferd sie vor dem Bösen beschützt.
   Sie durchschwimmt die Unterstadt und geht dort auf Jagd nach charyptiden Kreaturen.
** Graustein
   :PROPERTIES:
   :CUSTOM_ID: GS1
   :SEX:      m
   :OCCUPATION: Efferd Geweihter
   :ORGANIZATION: EK1
   :LOCATION: T02
   :SRC:      SH 65 SH 129
   :END:
   Bewahrer von Wind und Wogen
   - Aussehen :: 66 Jahre, 1,78 Schritt, schütteres, graues Haar, kieselgraue Augen, stimmgewaltig
   - Zitate :: Wie schwach und unmerklich der Sog auch sein mag: Wenn du nicht
     gegen ihn anruderst oder anschwimmst, wird dich der Strudel früher oder später verschlingen
   - Rollenspiel ::
     - lauenhaft wie Efferd (*laut* / leise)
     - *Mystiker* der sich Versenkung und Studium widmet       
   - Hintergrund ::
     - Hüter und *Sprachrohr Latas*, mit der er oft stundenlang Zwiesprache hält.
       Wer zu Lata will, muss Graustein überzeugen, dieser Begegnung würdig zu sein.
     - In Latas Grotte fand die *heilige Efferdperle*, die seitdem den *Tempel ziert*.
     - *Unterstadtkenner* und besitzt profundes Wissen über die Kreaturen des
       Meeres, alte Kulte sowie die dämonische Widersacherin Efferds, die er
       leidenschaftlich bekämpft.
   - Ziele ::
     - *Macht & Autoritaet* der Efferdkirche erhalten (gegen Numinoru & Charyptoroth)
     - die *Sternenmuschel* aufbauen und staerken (Schutz vor der Pforte des Grauens)
   - Orte :: [[file:locations.org::#T02][Alter Efferdtempel]]
   - Artefakte :: [[file:items.org::#EP1][Efferdperle]] (wird jeden Wassertag im Tempel praesentiert)

   Graustein weiss von der Pforte des Grauens & und um die Bedeutung der Sternenmuschel.
   
   Er weiss auch, dass der *Efferdkult Numinoru aus der Stadt verdrängt hat*.
   Das Wissen um die alten Vergehen seiner Kirche hält er unter Verschluss, weil er einen
   Autoritätsverlust befürchtet
   
*** Info [1/3]
    - [X] *Auftrag* Patroullie & Schutz von Unterfluren & Feldmark von naechtlichen Schrecken
      - Angriffe durch Kreaturen aus der Unterstadt (wahrscheinlich Necker; werden nicht erwaehnt)?
      - Wieso sind sie so aggresiv (als Geschoepfe Efferds?)
      - 12 Silbertaler pro Nacht
      - 24 fuer die erfolgreiche Abwehr von Angreifern (abzuholen am folgenden Morgen)
      - 3*300 Silbertaler, wenn die Gefahr entgueltig beseitigt wird
      - [ ] Siegel des Efferdtempel um sich auszuweisen
    - [ ] Karte von Haven (mit Karte der alten Unterstadt)?
    - [ ] *Gwen Petryl-Steine*, Bruchstücke von Alveran; dienen dem Segen & Schutz
          zunaechst *geheim: *Sternenmuschel*
** Gilia
   Efferdgeweihte
   :PROPERTIES:
   :CUSTOM_ID: GI1
   :SEX:      w
   :OCCUPATION: Efferd Geweihte
   :ORGANIZATION: EK1
   :LOCATION: T02
   :SRC:      SH 34 SH 106
   :END:
   - Aussehen :: 37 Jahre, rotbraunes Haar, viele Sommersprossen
   - Rollenspiel ::
     - herzlich & temperamentvoll
     - Wutanfaelle
   - Hintergrund :: eine kundige Gwen Petryl-Schleiferin
   - Ziele ::
     - Neckerbefreien 
   - Orte :: [[file:locations.org::#T02][Alter Efferdtempel]]
*** Info [0/1]
  - [ ] [[file:organizations.org::#EV1][Efferds Vergeltung (Neckerfreunde)]]
  - [ ] Es koennte sein, dass die Kinder Efferds aufbegehren, gegen das Unrecht
        (Versklavung) dass ihnen angetan wird
** Libana
   :PROPERTIES:
   :CUSTOM_ID: LI1
   :SEX:      w
   :OCCUPATION: Novizin Efferdtempel
   :ORGANIZATION: EK1
   :LOCATION: T02
   :SRC:      SH 34 SH 106
   :END:
   - Aussehen :: 16 Jahre, dunkles und nasses Haar, blass-bläuliche Haut, ausdruckslose Miene
   - Rollenspiel :: liebt Abenteuergeschichten
   - Hintergrund :: Liban ist die *Tocheter der geflohene charyptoroth Kultistin Selwine Dukatajeff*
     - kam im Alter von neun Jahren in die Obhut der Efferdkirche, als Selwines Frevel bekannt wurden.
     - Seitdem hat Selwine wiederholt versucht, Libana *den Dienern des Fischgesichtigen zu entreißen*:
       Mit Vergiftung, Erpressung und Entführungsversuchen.
     - wenn es sie nicht gäbe, hätte Selwine die Region um Havena längst verlassen.
     - Selwine ist eine Charyptorothpaktiererin, die sich auf die Manipulation
       der Fluten versteht. Wirklich wichtig ist ihr aber nur Libana, die
       verhängnisvoller Teil ihres Paktes ist: Vor vielen Jahren verzweifelte
       Selwine bei einem Schiffbruch, den sie mit ihrer Familie erlitt, an den
       Göttern. Sie bot der Herrin der Nachtblauen Tiefen ihren Mann und ihre
       Seele, wenn dafür nur ihre Tochter leben würde. Ihr Mann ertrank, sie
       selbst ging einen Pakt ein, und Libana überlebte.
     - Doch *Libana ist seitdem ebenfalls gezeichnet*: Sie ist freudlos, und ihre Haut muss
       stets feucht gehalten werden, damit sie nicht austrocknet.
     - Die Efferdgeweihten, die sich Libanas annahmen, mussten zudem feststellen, dass
       ein Lebensband zwischen Mutter und der unschuldigen Tochter besteht: Stirbt
       eine, siecht auch die andere binnen Stunden dahin. Reinigende Zeremonien im
       Tempel konnten das Band nicht auflösen.
     - *Libanas Herkunft ist ein offenes Geheimnis*, aber die Efferdgeweihten
       bemühen sich, der Heranwachsenden neue Lebensfreude zu geben und ihr
       dämonisches Stigma zu heilen. Gegen Selwine gehen sie nur vorsichtig vor,
       um Libana nicht zu gefährden.
   - Orte :: [[file:locations.org::#T02][Alter Efferdtempel]]

   fällt auf durch: *kränkliche Erscheinung*, *viele efferdgeweihte Amulette* und stets *nasse Kleidung*
** Caye
   :PROPERTIES:
   :CUSTOM_ID: CA1
   :SEX:      m
   :OCCUPATION: Koch
   :ORGANIZATION: EV1
   :LOCATION: G08
   :SRC:      SRC 35 SH 106
   :END:
   Koch
   - Aussehen :: 49 Jahre, Glatze, viele Tätowierungen, schüchtern
   - Zitate :: Singend
   - Rollenspiel :: singt beim Kochen und verstummt wenn jemand die Kueche betritt
   - Hintergrund ::
     - behauptet, ein Bastardsohn des ehemaligen Fürsten Halman zu sein, eines bekannten Herzensbrechers
   - Ziele ::
     - gutes Essen
     - Necker befreien
   - Orte :: [[file:locations.org::*Esche und Kork][Esche und Kork]]
*** Info [0/1]
    - [ ] Mitgliede in [[file:organizations.org::#EV1][Efferds Vergeltung (Neckerfreunde)]]

** Sula
   :PROPERTIES:
   :CUSTOM_ID: SU1
   :SEX:      w
   :OCCUPATION: Magd
   :ORGANIZATION: 
   :LOCATION: G08
   :SRC:      SRC 35
   :END:
   Schankmagd
   - Aussehen :: 31 Jahre, blondes Haar, großherzig
   - Rollenspiel :: hilfsbereit
   - Hintergrund ::
     ist ein ehemaliges Bettlermädchen aus dem Orkendorf. Die Travia-Akoluthin
     ist bei der Arbeit stets von einer Traube halb angenommener,
     *schmuddeliger Gossenkinder umgeben, die ihr zur Hand gehen*.
   - Orte :: [[file:locations.org::*Esche und Kork][Esche und Kork]]      
** Domnall Dalpert
   :PROPERTIES:
   :CUSTOM_ID: DD1
   :SEX:      m
   :OCCUPATION: Hesinde Geweither
   :ORGANIZATION: EV1
   :LOCATION: T10
   :SRC:      GN 13 SH 70 
   :END:
   - Aussehen :: 67 Jahre, hager, wirres weißes Haar und weißer Bart
   - Zitate :: Seid gesegnet mit Hesindes Weisheit
   - Rollenspiel ::
     - *hohe Stimme, nervös*
     - menschenscheu       
   - Hintergrund ::
     - Angst um den Tempel (wegen Zauberbann in Havena)
     - Experte der Kraeuterkunde und der Stadtgeschichte
     - Steckenpferd ist die grosse Flut: Er glaubt, dass sie - wie bei Selem -
       durch einen ins Meer fallenden Stern ausgelöst worden war, und dass die
       *Häufung von fallendem Gwen Petryl möglicherweise eine neue Flut ankündigt*
   - Ziele ::
     - plant eine Expedition vor die Küste, um den Meteor von 702 BF auf dem Meeresgrund zu finden
   - Orte :: [[file:locations.org::#T10][Hesindetempel]]

   Wer sein Vertrauen gewinnt hat einen loyalen Verbuendeten
   Unterstuetzt verfolgte Zauberkundige diskret
     
*** Info [0/5]
    - [ ] Vertrauen gewinnen: (Bekehren & Ueberzeugen)
      - Hesinde gefaellig
    - [ ] im *Leseraum* stehen nur uninteressante Schriften
    - [ ] Bibliothek:
      - [ ] Karte von altem Havena  
      - [ ] (Magiekunde -2; -1 bei gezielter Suche nach Necker; ca. 8 Stunden) 
            *Compendium Drakomagia* von Pher Drodont Werk über Drachen und ihre Magie und Weltsicht
            enthaelt einen Abschnitt ueber *Necker* 
      - [ ] Infos ueber [[file:criter.org::*Necker][Necker]] in historischen Werken:
        Sammelprobe (7 Proben, je 30 min, *Geschichtswissen*)
        - [ ] QS 6:
          - Necker sind scheue, friedvolle und duldsame Wesen
          - manchmal Tauschhandel zwischen Menschen & Neckern
          - Selbst die Versklavung von einzelnen Necker fuehrte bisher nicht zu Angriffen
        - [ ] QS 10: Passus aus der Stadtchronik, die seltenes aggresives Neckerverhalten beschreibt
              (Handout, GN 14)
    - [ ] *Magieverbot in Havena*: Hintergrund & Tipp auf [[file:locations.org::#FS01][Thaumaturgische Akademie]]
      - Vor ueber 500 Jahren: Gründung der Magierschule Thaumaturgische Akademie;
        bekannt und beruehmt fuer *machtvolle Artefaktemagie*
        *Mondenhalle*: Grosse Kuppelhalle, sechseckiger Grundriss, Alabasterstatue Madas (Mondgoettin)
      - Vor 400 Jahren: *Magierkriege*.
        - In Havena kämpfen mehrere Zauberer mit Dämonen, Geistern und Elementarwesen um die Macht.
          Ganze Häuserzeilen werden in Schutt und Aschegelegt, die Bewohner verfallen in Wahnsinn.
        - Schließlich reißt *Altumarn*, die Spektabilität der Thaumaturgischen Akademie,
          die Herrschaft an sich.
          Er tötet Konkurrenten oder macht sie mit magischen Mitteln gefügig.
          Seine *Magokratie* ist von strengen Gesetzen geprägt,
          - die etwa jegliche Dämonologie mit sofortigem Tod bestrafen.
          - Nichtmagische Bürger werden in ihren Rechten beschnitten und müssen hohe Abgaben entrichten.
      - wenige Jahre (5) spaeter:
        - Der *Thorwaler* und Hetmann *Niamad ui Bennain* zieht mit wenigen Getreuen nach Havena,
          um die Tyrannei der Magier mit dem Schwert zu beenden.
        - Ausgestattet mit Schutzartefakten verfolgt er Altumarn bis in die
          Gewölbe der Akademie und *tötet ihn*. 
        - Unter dem Jubel der Bevölkerung wird Niamad zum Herrscher über Albernia ausgerufen.
          - Niamad gründet den Rat der Kapitäne,
          - Verhaengt ein vollständiges Magieverbot für das ganze Stadtgebiet verfügt.
        - Alle Zauberer, die die Kämpfe überlebt haben, werden der Stadt verwiesen,
          das Akademiegebäude wird versiegelt.
        - hundert Jahre spater kommt dann die grosse Flut
          
    - [ ] Theorie zur grossen Flut: wie bei Selem durch einen ins Meer fallenden Stern ausgelöst,
           und dass die *Häufung von fallendem Gwen Petryl möglicherweise eine neue Flut ankündigt*
** Ordhan Faic
   Alter Schatzsucher
   :PROPERTIES:
   :CUSTOM_ID: OF1
   :SEX:      m
   :OCCUPATION: Unterstadtgaenger
   :ORGANIZATION: 
   :LOCATION: G25
   :SRC:      GN 15 SH 71
   :END:
   - Aussehen :: 96 Jahre, hager, fehlender Arm, riecht nach fauligem Fisch; fast blind
   - Zitate ::
     - bekannt als *irren Flößer* oder den *alten Schatzsucher*
   - Rollenspiel ::
     - *wirr* brabbelt vor sich hin 
   - Hintergrund ::
     - lebt auf krude gezimmerten Floß aus Trümmern und Treibgut in der Unterstadt
     - betrachtet die Unterstadt als sein Revier und versucht andere
       Schatzsucher in der Regel zu verteiben
     - Fundstücke setzt er in Fusel und Rauschkraut um, oder er spendet sie an
       Phex, in dessen Gunst er sich glaubt
   - Ziele ::
     - Schaetze finden 
   - Orte :: [[file:locations.org::#G25][Schatzinsel]], Unterstadt
*** Info [0/1]
    - [ ] Gebrabbel:
      - immer wieder hin und her, hin und her und immer wieder, wann hoeren die auf?
        (Necker schwimmen unter seinem Floss durch)
      - und es wallt im Wasser, hoch und runter, hoch und runter wie giftige Quallen
        und sie tragen es nach Hause in die Tiefe
        (die Necker haben Stoffe / Kleidung bei sich)
** Waern Poschrat
   Wirt Schatzinsel
   :PROPERTIES:
   :CUSTOM_ID: WP1
   :SEX:      m
   :OCCUPATION: Wirtin
   :ORGANIZATION:
   :LOCATION: G25
   :SRC:      GN 15
   :END:
   - Aussehen :: 50 Jahre, dick, Dreitagebart
   - Rollenspiel ::
     - ansteckendes Lachen
   - Hintergrund ::
     - Wirt der [[file:locations.org::#G25][Schatzinsel]]

   ist ein alter Schatzsucher,der sich mit Glücksrittern gern über die Tücken
   und Geheimnisse der Unterstadt austauscht und seine Geschichten mit jedem
   Jahr schauriger klingen lässt. Wenn in Havena jemand etwas Belangloses
   erzählt, ist eine beliebt gewordene Entgegnung „Interessiert das vielleicht
   Waern?“ oder „Waern interessiert’s!“
   
*** Info [0/3]
    - [ ] den Pferden geht es gut; 1 Dukate pro Pferd
    - [ ] der *modernde Schluerfer* hat mich vor 2 Tagen zu tode erschreckt
    *Allgemein zu [[file:criter.org::#cr-nk][Necker]]*
    - [ ] *Neckergesang*: normalerweise schoen, friedlich & betörend;
          in letzter Zeit klangen sie *klagend, gezwungen & trauernd*
          Vielleicht sind sie in not?
          Floesst jemand ihnen Alkohol ein?

** Yurro Aradin
   Schneider
   :PROPERTIES:
   :CUSTOM_ID: YA1
   :SEX:      m
   :OCCUPATION: Schneider
   :ORGANIZATION:
   :LOCATION: UF06
   :SRC:      GN 13 SH 27 ST 13
   :END:
   - Aussehen :: 40 Jahre, redet viel, meist mit Massband uber der Schulter
   - Rollenspiel ::
     - Bianca Castafiore Stimme
   - Hintergrund ::
     - Schneider der Reichen 
     - [[file:locations.org::#UF06][Schneider Aradin]]
       
*** Infos
    - [ ] gerade schwer beschaeftig; Laden quillt ueber vor *farbenfrohen Stoffen*
          hat wenig Zeit fuer Helden, die nichts kaufen
    - [ ] zwei Feste stehen bevor
      - [[file:plot.org::#2][Vollmondball auf Rethis]] (Maskenball mit Thema: die 6 Elemente)
      - Der Ball im [[file:locations.org::#OF08][Wachsfigurenkabinett]] zur Vorstellung neuer Figuren
    - [ ] Schneider von [[file:plot.org::#3][Scibor Aberkrom]]; der trug gerne leuchtende Farben (Rot, Orange, Gelb)
** Ybalio
   Necker
   :PROPERTIES:
   :CUSTOM_ID: YB1
   :SEX:      m
   :OCCUPATION: Necker aus der Unterstadt
   :ORGANIZATION: EV1
   :LOCATION: G25
   :SRC:      SH 68 SH 130
   :END:
   - Aussehen :: stattlicher Necker, langes weisses Haar, 
     rechtes Ohr fehlt, grosser Priatenohring am linke Ohr
   - Zitate ::
     Languste sagt: Brodeln-unten-kriechend-Dunkelheit. Tag tuuinas nicht gut
     für Tauchen in laainnaas uinaa uejo. Trockenohren bleiben besser an Luft.
     Lail aneeja müssen Herz weiter schlagen, hören auf mich.
   - Rollenspiel ::
     - guter Saenger
   - Hintergrund ::
   - Ziele ::
   - Orte :: Unterstadt

   Liebt [[*Branwen, die Hexe][Branwen]] und es qualt ihn, dass er nicht mit ihr zusammen sein kann.
   Finsteres wie verführerisches Angebot von *Nhywyll Dunkelwasser*:
   die sich wunderte, dass ihr betörender Gesang bei ihm – einem wahrlich Liebenden – nicht wirkte.
   Sie *versprach ihm, Branwen in eine Neckerin* zu verwandeln –
   wenn *Ybalio als ihr Agent* gewisse Dienste übernehmen würde.
   Ybalio lehnte ab und floh, doch seitdem trägt er die Verlockung und den Zweifel in sich.
   
*** Info [0/0]
