* Havena Kampange
  - Handlungsfreiheit
  - Ausblick auf die Art des Abenteuers (Sandbox)
  
** Master Plot
*** Personen Organisationen    
    - Charyptoroth https://de.wiki-aventurica.de/wiki/Charyptoroth
    - Efferd https://de.wiki-aventurica.de/wiki/Efferd
    - Numinoru https://de.wiki-aventurica.de/wiki/Numinoru
    - Feenwesen (Nymphen)
    - Havena Stadt Elite & Haendler
*** Ereignisse / Plots
    - Sternenfall (Gwen Petryl in Havena)
    - Weltzeitenwende (Karmakorthaeon)
    - Zwist der Goetter (Efferd, Numinoru seit dem Sternfall, Charyptoroth)
    - Der Namenlose / die 14 Lobpreisungen (siehe Offenbarung des Himmels)
    - Der Meteoreisenblock (Rohling eines schwarzen Auges) in Angbar
    - Imman (mit Ranziger Toss)
*** Orte
    - Unheiligtuemer der Charyptoroth
      - auf der Krakeninsel Nymphaeum > Auquamarinportal > Pforte des Grauens
    - Heiligtuemer des Efferd
    - Heiligtuemer des Numinoru
      
** Thema: Disfunktionalitaet
*** Handel - Schmuggel / Korruption
*** Disfunktionale Familie
    - Axels Charackter Abenteuer: Familie vor dem Bankrott. Deswegen Schmuggel
*** Wasser - Charyptoroth

** Handlung / Nodes
*** Beginn
    - Bei der naechtlichen Einfahrt nach Havena stoppt das Schiff der Helden
      nach Lichtzeichen an den aeussersten Auslaeufern der Unterstadt, um einen
      Schmuggler (einen Nebelgeist?) an Bord zu nehmen. Bei der Schmugglerware
      handelt es sich um Gwen Petryl (Wert ca. 5000 S) oder das Krakenauge (Charyptoroth Artefakt).
    - Bei Nacht ist die Einfahrt in den Hafen nicht moeglich, ausserdem ist die
      Durchfahrt durch die Unterstadt in der Nacht zu gefaehrlich. Deshalb
      Ankert das Schiff in unmittelbarer Naehe der Unterstadt.
    - Aufgrund der grossen Menge Gwen Petryl wird das Schiff bei Durchfahren der
      Unterstadt (am Ankergrund) von (mehreren?) Riesenoktopeden (Daimoniden) angegriffen.
    - Beim Kampf wird Leowald ins Wasser gerissen und anschliessend
      - von Lata in eine Feenwelt geschickt
      - von Nhywyll Dunkelwasser gefangen genommen
    - Lata, die Riesenschildkroete taucht zur Rettung auf und bezwingt die Oktopeden.
*** Plot Hooks
**** Konkurrierende Schmugglebaden
**** Imman mit Ranziger Toss
**** Das Grauen im Nebel (Nekerueberfaelle, aberglaeubische & verunsicherte Gradisten)
**** Simianide, die Mechanika
**** Kult der H'Ranga (Allesverschlingende)
**** Lorbold & Klopatex
**** Heist
** Unter Wasser
*** Atmung
    - Liturgie: http://ulisses-regelwiki.de/index.php/Lit_Unterwasseratmung.html
    - Zauber: https://ulisses-regelwiki.de/index.php/ZS_Wasseratem.html
    - Paktgeschenk: https://de.wiki-aventurica.de/wiki/Wasseratmung%20(Paktgeschenk)
    - Alchemie:
      - https://de.wiki-aventurica.de/wiki/Purpurwasser (Efferds Wogen Seiten 42, 141)
      - https://de.wiki-aventurica.de/wiki/Wasserodem (in Havena verbotenes Tauchelexir, SSH 90-91, Grauen aus dem Nebel 28)
    - Pflanzlich: https://de.wiki-aventurica.de/wiki/Kajubo
    - Mechanisch: Simiande (SSH 89-90)
    - Elementar / Daemonisch: durch Beschwoerung & entsprechenden Auftrag

** Reisen
   - Reise muss ein relevanter Teil des Abenteuers sein, sonst weglassen (z.B. Eskortierung)
   - Die Reisemechanik darf kein Selbstzweck sein (coole Mechanik um spiel anzuregen)
   - Handlung pausiert nicht waehrend der Reise (Plot / Thema einbetten)
   - Die Reise sollte nicht linear sein (Entscheidung auf der Reise, z.B. sicherer & langer vs. unsicherer & schneller Weg)
   - Spannung aufbauen durch Sammeln von Information (Interaktio foerdern)
   - Keine Sackgassen

** Features
*** Finishing Move
*** Initiative Abfrage

** NPCs
*** Template
    https://thealexandrian.net/wordpress/37916/roleplaying-games/universal-npc-roleplaying-template
    - *Name*
    - *Appearance*: Essentially a boxed text description that you can use when
      the PCs meet the the NPC for the first time. Get it pithy. 1-2 sentences
      is the sweet spot. Three sentences is pretty much the maximum length you
      should use unless there is something truly and outrageously unusual about
      the character. Remember that you don’t need to describe every single thing
      about them: Pick out their most interesting and unique features and let
      your players’ imaginations paint in the rest.
    - *Quote*: I don’t always use this entry, but a properly crafted quote can
      be a very effective way to quickly capture the NPC’s unique voice.
      Generally speaking, though, all you want is a single sentence. You should
      be able to basically glance at it and grok the voice. (Special exception
      if the character’s voice is “rambling old man”.)
    - *Roleplaying*: This is the heart of the template, but it should also be
      the shortest section. Two or three brief bullet points at most. You’re
      looking to identify the essential elements which will “unlock” the
      character for you.

      There are no firm rules here, but I will always try to include at least
      one simple, physical action that you can perform while playing the
      character at the table. For example, maybe they tap their ear. Or are
      constantly wearing a creepy smile. Or they arch their eyebrow. Or they
      speak with a particular accent or affectation. Or they clap their hands
      and rub them together. Or snap their fingers and point at the person
      they’re talking to. Or make a point of taking a slow sip from their drink
      before responding to questions. You don’t have to make a big deal of it
      and it usually won’t be something that you do constantly (that gets
      annoying), but this mannerism is your hook: You’ll find that you can
      quickly get back into the character by simply performing the mannerism. It
      will make your players remember the NPC as a distinct individual. And it
      can even make playing scenes with multiple NPCs easier to run (because you
      can use the mannerisms to clearly distinguish the characters you’re
      swapping between).

      You’ll generally only need one mannerism. Maybe two. More than that and
      you lost the simple utility of the mannerism in unnecessary complexity.
      It’s not that the character’s entire personality is this one thing; it’s
      that the rest of the character’s personality will flow out of you whenever
      you hit that touchstone.

      Round this out with personality traits and general attitude. Are they
      friendly? Hostile? Greedy? Ruthless? Is there a particular negotiating
      tactic they like? Will they always offer you a drink? Will they fly into a
      rage if insulted? But, again, keep it simple and to the point. You want to
      be able to glance at this section, process the information almost
      instantaneously, and start playing the character. You don’t need a
      full-blown psychological profile and, in fact, that would be
      counterproductive.
    - *Background*: This section is narrative in nature. You can let it breathe
      a bit more than the other sections if you’d like, but a little will still
      go a long way. I tend to think of this in terms of essential context and
      interesting anecdotes. Is it something that will directly influence the
      decisions they make? Is it information that the PCs are likely to discover
      about them? Is it an interesting story that the NPC might tell about
      themselves or (better yet) use as context for explaining something? Great.
      If it’s just a short story about some random person’s life that you’re
      writing for an audience of one, refocus your attention on prepping
      material that’s relevant to the players.
    - *Key Info*: In bullet point format, lay out the essential interaction or
      information that the PCs are supposed to get from the NPC. The nature of
      this section will vary depending on the scenario and the NPC’s role in it,
      but the most obvious example is a mystery scenario in which the NPC has a
      clue. Rather than burying that clue in the narrative of the NPC’s
      background, you’re yanking it and placing it in a list to make sure you
      don’t lose track of it during play. (The Three Clue Rule applies, of
      course, so just because something appears in this section it doesn’t mean
      that the PCs are automatically going to get it.)

      You could also use this section to lay out the terms of employment being
      offered by the Mysterious Man in the Tavern. Or to list the discounts
      offered by a shopkeeper. It’s a flexible tool. In some cases, it might get
      quite long. But try to keep it well-organized (using the bullet points
      will help with that). If it just becomes a giant wall of text, its purpose
      has been lost.
    - *Stat Block*: If you need stats for the NPC, put ’em at the bottom of the
      briefing sheet in whatever format makes sense for the system you’re
      running.

* Sql

** insert & select
#+name: sqlite-populate-test
#+header: :results silent
#+header: :dir .
#+header: :db test-sqlite.db
#+begin_src sqlite
  -- create table greeting(one varchar(10), two varchar(10));
  insert into greeting values('Hello', 'DSA!');
#+end_src

#+name: sqlite-hello
#+header: :column
#+header: :colnames yes
#+header: :separator \
#+header: :results raw
#+header: :dir .
#+header: :db test-sqlite.db
#+begin_src sqlite
select * from greeting;
#+end_src

#+RESULTS: sqlite-hello
one         two       
----------  ----------
Hello       world!    
Hello       DSA!      

** variables (scalar)
#+BEGIN_SRC sqlite :db ./rip.db :var rel="tname" n=300 :colnames yes
drop table if exists $rel;
create table $rel(n int, id int);
insert into $rel(n,id) values (1,210), (3,800), (4, 900);
select * from $rel where id > $n;
#+END_SRC

#+RESULTS:
| n |  id |
|---+-----|
| 3 | 800 |
| 4 | 900 |

** variables (tables)
#+NAME: tableexample
| id |  n |
|----+----|
|  1 |  5 |
|  2 |  9 |
|  3 | 10 |
|  4 |  9 |
|  5 | 10 |

#+begin_src sqlite :db ./rip.db :var orgtable=tableexample :colnames yes
drop table if exists testtable;
create table testtable(id int, n int);
.mode csv testtable
.import $orgtable testtable
select n, count(*) from testtable group by n;
#+end_src

#+RESULTS:
|  n | count(*) |
|----+----------|
|  5 |        1 |
|  9 |        2 |
| 10 |        2 |

** orgtables as updates
