#+STARTUP: content
#+SEQ_TODO:   TODO(t) ACTIVE(i) WAITING(w@) | DONE(d) DEAD(c@)
#+TITLE: Havena Kampange
* Havena Kampange
  - Handlungsfreiheit
  - Ausblick auf die Art des Abenteuers (Sandbox)

** Stimmung
   - efferdergeben, freiheitsliebend,
   - geschäftstüchtig, melancholisch.
   - häufig sind Zeichen von Verfall früheren Glanzes
   - misstrauisch gegenüber Magie und dem Boronkult
   - zwiespältig gegenüber dem Mittelreich und der Kaiserin
   - Hafen, Meer, Nebel, Wetter (SH 8)
   - Gwen Petryl
   - "Efferd hat uns alles gegeben und uns alles genommen. So oder so, vergessen hat er uns nie."
** Nodes
   :PROPERTIES:
   :COLUMNS:  %45ITEM %4CUSTOM_ID(ID) %4LAYER %6LOCATION %17SRC
   :END:
*** Unspezifisch
**** TODO Sonderausgabe der Havena-Fanfare
     :PROPERTIES:
     :custom_id: 1
     :location: ueberall
     :layer: GN
     :src: GN 10
     :END:
     "Extrablatt, Extrablatt! Brave Buerger und Gaeste Havenas!
     Lest die neuste Ausgabe der Fanfare! Erneut ein Toter in Orkendorf. 
     Erfahrt die Hintergruende fuer nur 12 Heller"
     - Verkauf durch Botenjunge *Jendar*
     - 12 Heller
     - reisserischer Bericht ueber Morde in Havena
***** Links [0/2]
      - [ ] Handout [[file:handout/Fanfare-Schrecken-aus-dem-Nebel.pdf][Fanfare - Schrecken aus dem Nebel]]
      - [ ] [[#UF11][Redaktionshaus]] da wird gerade eine grosse Monatsausgabe geplant
**** TODO Karten fuer Vollmondball auf Rethis
     :PROPERTIES:
     :custom_id: 2
     :location: hafen D12
     :layer: GN
     :END:
     - junge Verkäuferin *Fianna*
     - Kostuemball zum Thema: *Die 6 Elemente*
     - 1 Dukate
     - in 2 Tagen am Abend
***** Links [0/2]
      - [ ] [[#UF06][Schneider Aradin]]
      - [ ] [[#G24][Rethis]]
**** Begegnung mit der anderen Soeldnergruppe
     :PROPERTIES:
     :custom_id: 4
     :location: MA OR NA
     :layer: GN
     :END:
*** Unterfluren
**** Redaktionshaus Havena-Fanfare & Dreikronen-Drukerei
     :PROPERTIES:
     :custom_id: UF11
     :location: G14
     :layer: GN
     :src: GN 14 SH 26 ST 13
     :END:
     - [[file:locations.org::#UF11][Ort]]
     - [[file:npcs.org::#NS1][Niamh Schlappmaul]]
**** Schneider Aradin
     :PROPERTIES:
     :custom_id: UF06
     :location: G11
     :layer: GN
     :src: GN 13 SH 17 ST 13
     :END:
**** Hesindetempel
     :PROPERTIES:
     :custom_id: T10
     :location: G14
     :layer: GN
     :src: GN 13 SH 70 ST 33
     :END:
     
*** Feldmarschen
**** Rethis
     :PROPERTIES:
     :custom_id: G24
     :location: D11
     :layer: GN
     :src: GN 17 SH 35
     :END:
**** Tarverne Schatzinsel
     :PROPERTIES:
     :custom_id: G25
     :location: C13
     :layer: GN
     :src: GN 15 SH 22 ST 13
     :END:     
*** Fischerort
**** Alter Efferdtempel
     :PROPERTIES:
     :custom_id: T02
     :location: F2
     :layer: GN
     :SRC:      GN 24 SH 33 ST 11
     :END:
***** Links [0/1]
      - [ ] Graustein
*** Orkendorf
     
*** GN (Grauen aus dem Nebel)
**** Opfer der Angriffe [5/9]
     :PROPERTIES:
     :custom_id: 3
     :layer: GN
     :src: GN 12
     :END:
***** TODO Scibor Aberkrom
      :PROPERTIES:
      :location: Suedhafen
      :END:
      - Fanfare :: Wir trauern um Scibor Aberkrom. Der verdienstvolle Patrizier
        starb in Folge eines Angriffs durch die tiefen Kreaturen. Der Kaufmann
        war gerade im Südhafen ins Gespräch mit einem Schiffseigner verwickelt,
        als der Fluch aus dem Meer zuschlug. Mindestens drei der Wesen krauchten
        auf Aberkrom zu. Seeleute und Hafner nahmen Reißaus. Die Kutsche
        Aberkroms mit seinen Begleiterinnen ging durch. Die Kreaturen zerrten
        den Wehrlosen ins Hafenbecken und ersäuften ihn. Seinen Leichnam fand
        man erst Stunden später im Wasser treibend.
***** TODO Etaine Achton
      :PROPERTIES:
      :location: Fischerort
      :END:
      - Fanfare :: Nur die Götter wissen, was Etaine Achton aus Fischerort, Frau
        des Fischhändlers Hemwit, widerfahren ist. In Krakeninsel wurde sie wohl
        beim Gang vom Traviatempel von Neckern überfallen. Nur zitternd traf sie
        zuhause ein. So groß war der Schrecken, dass die Necker ihr die Kleider
        vom Leibe reißen wollten
***** TODO Emer Mellrich      
      :PROPERTIES:
      :location: Marschen
      :END:
      - Fanfare :: In Marschen wankte eine nasse Gestalt aus der Unterstadt an
        die Sattlerin Emer Mellrich heran. Doch der gab die Handwerkerin kräftig
        auf die Schwimmhäute. Die Kreatur floh, Emer hintendrein. Im dichten
        Nebel verlor sie das Wesen aus den Augen und schlug dann auf eine
        Gestalt ein, die sie für die Kreatur hielt. Leider handelte es sich
        stattdessen um einen Fischer, der drei Zähne verlor.
***** TODO Beatha Arberdan
      :PROPERTIES:
      :location: Orkendorf
      :END:
      - Hals gebrochen beim Kampf gegen Necker
***** DONE Novize des Praios 
      :PROPERTIES:
      :location: E8 Nallesdorf
      :END:
      - *Praioslieb*
      - Fanfare ::
        - blaue Molchenfinger
        - (tiefe) Kreatur mit langem moosgrünem Fischhaar
***** DONE Kontor Engstrand
      :PROPERTIES:
      :location: E7 Nallesdorf
      :END:
      - Fanfare ::
        - mit Muscheln und Tang war das Wesen bewachsen
        - seine Augen leuchteten grün
***** DONE Fedelma Humpen
      :PROPERTIES:
      :location: Marschen
      :END:
      - Fanfare ::
        - angegriffen
        - Kleidung vom Leib gerissen
        - starker Gestank (Fisch)
***** DEAD Ysilt Bennoch
      :PROPERTIES:
      :location: Krakeninsel
      :END:
      - Fischerin
      - Fanfare ::
        - erstochen von Dreizack (Neckerdreizack)
***** DEAD Ulfer Meckmur
      :PROPERTIES:
      :location: Orkendorf
      :END:
      - Tagelöhner
      - Fanfare ::
        - ertrunken im Seehafen
** Wetter
*** Tabelle
|   W20 | Wind Typische Windrichtung | Stärke              | Wettercharakter                                                                                                   |
|-------+----------------------------+---------------------+-------------------------------------------------------------------------------------------------------------------|
|   1-8 | Beleman West               | schwach bis stark   | stetes Wolkentreiben, heiter bis bedeckt; trocken bis Dauerregen; mild; vertreibt oft Nebel und bietet gute Sicht |
|  9-13 | Nuianna Nordwest           | schwach             | dunstig bis tief vernebelt; feucht; kalt                                                                          |
| 14-15 | Horoban Südost             | schwach bis mäßig   | sonnig bis bewölkt; trocken, aber dunstig; warm                                                                   |
| 16-17 | Rondrikan Nordwest         | stark bis stürmisch | dunkelwolkig; Regen und Gewitter; kühl, Sturmflut möglich, im Winter Schneesturm                                  |
|    18 | Caranthu Ostnordost        | schwach bis mäßig   | sonnig bis bewölkt; trocken; im Sommer warm, im Winter eisig                                                      |
|    19 | Baltrir West               | mäßig bis stürmisch | heiter bis bedeckt; trocken bis Schauer; schneidend kalt aus den Höhen fallend und in Böen alles mit sich reißend |
|    20 | Katla wechselnd            | mäßig bis stürmisch | unbeständig, schneller Wetterwechsel, Windhosen, plötzliche Sturmflut                                             |
*** Gezeiten
    Zwischen dem höchsten und niedrigsten Wasserstand liegen ca. 6Std. und 15 Min.
    Dadurch hat fast jeder Tag vier Gezeiten (2x Ebbe, 2x Flut), manche aber auch nur drei.
    Ebbe und Flut finden jeden Tag etwa eine Dreiviertelstunde später statt.
    - Niedrigwasser ::
      - Schiffe mit viel Tiefgang bleiben im Hafen, um nicht auf Grund zu laufen.
      - Fleetenkieker holen Unrat aus dem Schlick des Hafens und der Fleete.
    - Hochwasser ::
      - Fahrrinnen des Großen Flusses sind am besten zu befahren, bei Tageslicht herrscht Hochbetrieb.
      - Viele Schiffe nutzen die günstige Stunde und legen ab.
        Im Hafenbecken wird es eng, an der Zollbrücke stocken die Dreimaster.
        Lotsen haben alle Hände voll zu tun, und Flüche hallen über das Wasser.
    - Aktueller Gezeitenstand :: 1W20:
      - 1 :: Niedrigwasser
      - 2-10 :: auflaufendes Wasser
      - 11 :: Hochwasser
      - 12-20 :: ablaufendes Wasser

** Handlung
*** Beginn
    - Bei der naechtlichen Einfahrt nach Havena stoppt das Schiff der Helden
      nach Lichtzeichen an den aeussersten Auslaeufern der Unterstadt, um einen
      Schmuggler (einen Nebelgeist?) an Bord zu nehmen. Bei der Schmugglerware
      handelt es sich um Gwen Petryl (Wert ca. 5000 S) oder das Krakenauge (Charyptoroth Artefakt).
    - Bei Nacht ist die Einfahrt in den Hafen nicht moeglich, ausserdem ist die
      Durchfahrt durch die Unterstadt in der Nacht zu gefaehrlich. Deshalb
      Ankert das Schiff in unmittelbarer Naehe der Unterstadt.
    - Aufgrund der grossen Menge Gwen Petryl wird das Schiff bei Durchfahren der
      Unterstadt (am Ankergrund) von (mehreren?) Riesenoktopeden (Daimoniden) angegriffen.
    - Beim Kampf wird Leowald ins Wasser gerissen und anschliessend
      - von Lata in eine Feenwelt geschickt
      - von Nhywyll Dunkelwasser gefangen genommen
    - Lata, die Riesenschildkroete taucht zur Rettung auf und bezwingt die Oktopeden.
*** Encounters
    (Zufalls) Begegnungen
    - [[file:organizations.org::Encounter-Nebelgeister][Encounter-Nebelgeister]]
      Nebelgeister bei aktiver Schmuggelaktion
    - [[file:organizations.org::Encounter-Stadtgarde][Encounter-Stadtgarde]]
      Garde auf Patroullie mit Focus: Magie / schwere Waffen / Schmuggelware
*** Plot Hooks
**** Pferdepension (Feldmarken)     
**** Konkurrierende Schmugglebaden
**** Imman mit Ranziger Toss
**** Das Grauen im Nebel (Nekerueberfaelle)
**** Simianide, die Mechanika
**** Kult der H'Ranga (Allesverschlingende)
**** Lorbold & Klopatex
**** Heist
**** Cuanu ui Bennain (verschollener ehemaliger König)
     SH 7 SH 78 
** Master Plot
*** Personen Organisationen    
    - [[https://de.wiki-aventurica.de/wiki/Charyptoroth][Charyptoroth]]
    - [[https://de.wiki-aventurica.de/wiki/Efferd][Efferd]]
    - [[https://de.wiki-aventurica.de/wiki/Numinoru][Numinoru]]
    - Feenwesen (Nymphen)
    - Havena Stadt Elite & Haendler
*** Ereignisse / Plots
    - Sternenfall (Gwen Petryl in Havena)
    - Weltzeitenwende (Karmakorthaeon)
    - Zwist der Goetter (Efferd, Numinoru seit dem Sternfall, Charyptoroth)
    - Der Namenlose / die 14 Lobpreisungen (siehe Offenbarung des Himmels)
    - Der Meteoreisenblock (Rohling eines schwarzen Auges) in Angbar
    - Imman (mit Ranziger Toss)
    - Kultisten (Faschisten):
      - leben in einer alternativen Realitaet (cultist mindset)3
      - alles was nicht dem kultischen Weltbild entspricht, wird als fundamental falsch empfunden
      - nur der eigene Glaube, die eigenen Gefuehle sind wahr & richtig
      - wenn sie zur Rede gestellt werden, reagieren sie mit Gewalt, da sie keine rationalen Argumente haben
        
*** Orte
    - Unheiligtuemer der Charyptoroth
      - auf der Krakeninsel Nymphaeum > Auquamarinportal > Pforte des Grauens
    - Heiligtuemer des Efferd
    - Heiligtuemer des Numinoru
      
** Thema: Disfunktionalitaet
*** Handel - Schmuggel / Korruption
*** Disfunktionale Familie
    - Axels Charackter Abenteuer: Familie vor dem Bankrott. Deswegen Schmuggel
*** Wasser - Charyptoroth

** Unter Wasser
*** Atmung
    - Liturgie :: [[https://ulisses-regelwiki.de/index.php/Lit_Unterwasseratmung.html][Unterwasseratmung]]
    - Zauber :: [[https://ulisses-regelwiki.de/index.php/ZS_Wasseratem.html][Wasseratem]]
    - Paktgeschenk :: [[https://de.wiki-aventurica.de/wiki/Wasseratmung%20(Paktgeschenk)][Paktgeschenk]]
    - Alchemie ::
      - [[https://ulisses-regelwiki.de/index.php/Wasserodem.html][Wasserodem]] in Havena verbotenes Tauchelexir, GN 28, SH 90
      - [[https://de.wiki-aventurica.de/wiki/Purpurwasser][Purpurwasser]] (Efferds Wogen Seiten 42, 141)
    - Pflanzlich :: [[https://ulisses-gamereference.com/index.php/Herb_Kajubo.html][Kajubo]]
    - Mechanisch :: Simiande die Mechanika (SH 89-90)
    - Elementar / Daemonisch :: durch Beschwoerung & entsprechenden Auftrag

** Reisen
   - Reise muss ein relevanter Teil des Abenteuers sein, sonst weglassen (z.B. Eskortierung)
   - Die Reisemechanik darf kein Selbstzweck sein (coole Mechanik um spiel anzuregen)
   - Handlung pausiert nicht waehrend der Reise (Plot / Thema einbetten)
   - Die Reise sollte nicht linear sein (Entscheidung auf der Reise, z.B. sicherer & langer vs. unsicherer & schneller Weg)
   - Spannung aufbauen durch Sammeln von Information (Interaktio foerdern)
   - Keine Sackgassen

** Features
*** Finishing Move
*** Initiative Abfrage

** NPCs
*** Template
    https://thealexandrian.net/wordpress/37916/roleplaying-games/universal-npc-roleplaying-template
    - *Name*
    - *Appearance*: Essentially a boxed text description that you can use when
      the PCs meet the the NPC for the first time. Get it pithy. 1-2 sentences
      is the sweet spot. Three sentences is pretty much the maximum length you
      should use unless there is something truly and outrageously unusual about
      the character. Remember that you don’t need to describe every single thing
      about them: Pick out their most interesting and unique features and let
      your players’ imaginations paint in the rest.
    - *Quote*: I don’t always use this entry, but a properly crafted quote can
      be a very effective way to quickly capture the NPC’s unique voice.
      Generally speaking, though, all you want is a single sentence. You should
      be able to basically glance at it and grok the voice. (Special exception
      if the character’s voice is “rambling old man”.)
    - *Roleplaying*: This is the heart of the template, but it should also be
      the shortest section. Two or three brief bullet points at most. You’re
      looking to identify the essential elements which will “unlock” the
      character for you.

      There are no firm rules here, but I will always try to include at least
      one simple, physical action that you can perform while playing the
      character at the table. For example, maybe they tap their ear. Or are
      constantly wearing a creepy smile. Or they arch their eyebrow. Or they
      speak with a particular accent or affectation. Or they clap their hands
      and rub them together. Or snap their fingers and point at the person
      they’re talking to. Or make a point of taking a slow sip from their drink
      before responding to questions. You don’t have to make a big deal of it
      and it usually won’t be something that you do constantly (that gets
      annoying), but this mannerism is your hook: You’ll find that you can
      quickly get back into the character by simply performing the mannerism. It
      will make your players remember the NPC as a distinct individual. And it
      can even make playing scenes with multiple NPCs easier to run (because you
      can use the mannerisms to clearly distinguish the characters you’re
      swapping between).

      You’ll generally only need one mannerism. Maybe two. More than that and
      you lost the simple utility of the mannerism in unnecessary complexity.
      It’s not that the character’s entire personality is this one thing; it’s
      that the rest of the character’s personality will flow out of you whenever
      you hit that touchstone.

      Round this out with personality traits and general attitude. Are they
      friendly? Hostile? Greedy? Ruthless? Is there a particular negotiating
      tactic they like? Will they always offer you a drink? Will they fly into a
      rage if insulted? But, again, keep it simple and to the point. You want to
      be able to glance at this section, process the information almost
      instantaneously, and start playing the character. You don’t need a
      full-blown psychological profile and, in fact, that would be
      counterproductive.
    - *Background*: This section is narrative in nature. You can let it breathe
      a bit more than the other sections if you’d like, but a little will still
      go a long way. I tend to think of this in terms of essential context and
      interesting anecdotes. Is it something that will directly influence the
      decisions they make? Is it information that the PCs are likely to discover
      about them? Is it an interesting story that the NPC might tell about
      themselves or (better yet) use as context for explaining something? Great.
      If it’s just a short story about some random person’s life that you’re
      writing for an audience of one, refocus your attention on prepping
      material that’s relevant to the players.
    - *Key Info*: In bullet point format, lay out the essential interaction or
      information that the PCs are supposed to get from the NPC. The nature of
      this section will vary depending on the scenario and the NPC’s role in it,
      but the most obvious example is a mystery scenario in which the NPC has a
      clue. Rather than burying that clue in the narrative of the NPC’s
      background, you’re yanking it and placing it in a list to make sure you
      don’t lose track of it during play. (The Three Clue Rule applies, of
      course, so just because something appears in this section it doesn’t mean
      that the PCs are automatically going to get it.)

      You could also use this section to lay out the terms of employment being
      offered by the Mysterious Man in the Tavern. Or to list the discounts
      offered by a shopkeeper. It’s a flexible tool. In some cases, it might get
      quite long. But try to keep it well-organized (using the bullet points
      will help with that). If it just becomes a giant wall of text, its purpose
      has been lost.
    - *Stat Block*: If you need stats for the NPC, put ’em at the bottom of the
      briefing sheet in whatever format makes sense for the system you’re
      running.
*** Namen
    https://albernia.westlande.info/index.php?title=Albernische_Namen
** Resources
   - Maps https://www.deviantart.com/foundryatropos
   - DSA https://www.deviantart.com/steffenbrand
* Sql

** insert & select
#+name: sqlite-populate-test
#+header: :results silent
#+header: :dir .
#+header: :db test-sqlite.db
#+begin_src sqlite
  -- create table greeting(one varchar(10), two varchar(10));
  insert into greeting values('Hello', 'DSA!');
#+end_src

#+name: sqlite-hello
#+header: :column
#+header: :colnames yes
#+header: :separator \
#+header: :results raw
#+header: :dir .
#+header: :db test-sqlite.db
#+begin_src sqlite
select * from greeting;
#+end_src

#+RESULTS: sqlite-hello
one         two       
----------  ----------
Hello       world!    
Hello       DSA!      

** variables (scalar)
#+BEGIN_SRC sqlite :db ./rip.db :var rel="tname" n=300 :colnames yes
drop table if exists $rel;
create table $rel(n int, id int);
insert into $rel(n,id) values (1,210), (3,800), (4, 900);
select * from $rel where id > $n;
#+END_SRC

#+RESULTS:
| n |  id |
|---+-----|
| 3 | 800 |
| 4 | 900 |

** variables (tables)
#+NAME: tableexample
| id |  n |
|----+----|
|  1 |  5 |
|  2 |  9 |
|  3 | 10 |
|  4 |  9 |
|  5 | 10 |

#+begin_src sqlite :db ./rip.db :var orgtable=tableexample :colnames yes
drop table if exists testtable;
create table testtable(id int, n int);
.mode csv testtable
.import $orgtable testtable
select n, count(*) from testtable group by n;
#+end_src

#+RESULTS:
|  n | count(*) |
|----+----------|
|  5 |        1 |
|  9 |        2 |
| 10 |        2 |

** orgtables as updates
